### 프로젝트 생성
POST /project-api/projects HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "accountId": "tester1",
  "projectName": "test project1"
}

### 프로젝트 수정
PUT /project-api/projects/1 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "projectId": 2,
  "projectName": "test project2",
  "projectStateCode": "02"
}

### 프로젝트 삭제
DELETE /project-api/projects/2 HTTP/1.1
Host: localhost:8080
Content-Type: application/json


